name: Release MPV Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 12 1/2 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sudo apt update
        sudo apt install libfuse2
        wget https://raw.githubusercontent.com/ivan-hc/MPV-appimage/main/mpv-junest.sh
        chmod a+x ./mpv-junest.sh
        ./mpv-junest.sh
        mkdir dist
        mv *AppImage dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: MPV-Media-Player-x86_64.AppImage
        path: 'dist'

  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: MPV-Media-Player-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: true
            draft: false
            files: |
              MPV-Media-Player-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
